# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'Agnostic, feminist, food enthusiast, cook, and lover of paranormal fiction.'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
